name: bashshell
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
 #   - name: 打印ip
  #    run: |
   #        ip addr
    - name: Download dl
      env: 
       DL_URL: https://image.moeclub.org/GoogleDrive/
       DL_URL1: 1VZHn2AJ3iXpJAYsDwWAPL6m_CjMAovsb
       DL_NAME: dl.tar.gz
       REPO_NAME: openwrt 
      run: | 
        wget  $DL_URL/$DL_URL1
        mkdir $REPO_NAME
        mv  $DL_URL1 $REPO_NAME/$DL_NAME
        tar -xzvf $DL_NAME
        sudo rm -rf $DL_NAME
        cd $REPO_NAME
        ls -ll
    #- name: SSH connection to Actions
     # uses: p3terx/debugger-action@master  

