name: bashshell
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
 #   - name: 打印ip
  #    run: |
   #        ip addr
        df -h
         ls -la
    #- name: SSH connection to Actions
     # uses: p3terx/debugger-action@master  

