name: bashshell
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04  
    steps:
    - name: download dl
      env: 
       REPO_URL: https://image.moeclub.org/GoogleDrive/
       REPO_URL1: 1VZHn2AJ3iXpJAYsDwWAPL6m_CjMAovsb
       REPO_NAME: dl.tar.gz
      run: | 
        wget  $REPO_URL/$REPO_URL1
        mv  $REPO_URL1 $REPO_NAME
        tar -xzvf $REPO_NAME
        sudo rm -rf $REPO_NAME 
          ls -ll
          df -h
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: dl
        path: dl      
    #- name: SSH connection to Actions
     # uses: p3terx/debugger-action@master  
