name: bashshell
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
 #   - name: 打印ip
  #    run: |
   #        ip addr
    - name: Download dl
      env: 
       DL_URL: https://image.moeclub.org/GoogleDrive/
       DL_URL1: 1o0XRa9N7dwBAiQMOr9AATyuY54BfaDsQ
       DL_NAME: build_dir.tar.gz
       REPO_NAME: openwrt 
      run: | 
        mkdir $REPO_NAME && cd $REPO_NAME
        wget  $DL_URL/$DL_URL1
        mv $DL_URL1 $DL_NAME
        tar -xzvf $DL_NAME
        sudo rm -rf $DL_NAME
        ls -la
    #- name: SSH connection to Actions
     # uses: p3terx/debugger-action@master  

