name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 打印ip
      run: |
           ip addr
    - uses: actions/checkout@v1
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1      

